package com.haulmont.testtask.dao;

import com.haulmont.testtask.model.AbstractElement;
import com.vaadin.server.Page;
import com.vaadin.ui.Notification;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

/*
 * Абстрактный класс DAO описывающий общие методы взаимодействия с БД.
 * @author Andrey Kiryakov
 * @param <E>
 * @param <K>
 */
public interface AbstractDAO {
    
    public List getAll();
    public AbstractElement getElementById(long id);
    public boolean update(AbstractElement element);
    public boolean delete(long id);
    public boolean create(AbstractElement element);
    
    public static void createProjectsTables() {
        try {
            AbstractConnection connection = new HSQLDBConnection();
            if (connection.connect()) {
                try (Statement statement = connection.getConnection().createStatement()){
                    String sql = "CREATE MEMORY TABLE clients (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                            + "sourname VARCHAR(32), name VARCHAR(32), middlename VARCHAR(32), tel VARCHAR(18))";  
                    statement.executeUpdate(sql);
                    statement.close();
                } finally {
                    connection.closeConnection();
                } 
             }
        } catch (SQLException e) {
            new Notification("WARNING", e.getMessage(), Notification.TYPE_ERROR_MESSAGE, true).show(Page.getCurrent());
        } 
    }
       
}